export enum VALIDATION_CODES {
  "VALIDATION_SUCCESFUL" = 0,
  "BODY_IS_EMPTY" = 1,
  "PROPERTY_IS_MISSING" = 2,
  "BODY_HAS_ADDITIONAL_PROPERTIES" = 3,
  "CATEGORIES_NAME_ERROR" = 41,
  "CATEGORIES_SHOW_ERROR" = 42,
  "CATEGORIES_PARENT_ERROR" = 43,
}
